### PR TITLE
Deprecation fixes

### PR DESCRIPTION
**Pull request by Norgul**
Replaced deprecated curly braces, and added regex support for HTTP/2.

### CODE REVIEW

**Comment by bodva** [comment]
It would be great to have this merged.

cc @mnovozhylov

**Comment by mnovozhylov** [comment]
@bodva , please check https://github.com/upwork/php-upwork/blob/master/vendor-src/README.

**Comment by mnovozhylov** [comment]
@bodva , please check https://github.com/upwork/php-upwork/blob/master/vendor-src/README.

**Comment by Norgul** [comment]
@mnovozhylov unless it has a licence which prohibits changing (which defies the whole purpose of **open source** code), linking that readme and closing this PR made no sense whatsoever. You're literally declining having a non-breaking improvement merged.

**Comment by mnovozhylov** [comment]
@Norgul , I appreciate your feedback and engagement. I have to mention, still, that we do not maintain vendor's code. Instead, the library provides proper interface and the mentioned vendor library is just an example. You are free to organize your project in the proper way, and fork or update the vendor's code on your side.

**Comment by Norgul** [comment]
@mnovozhylov that all sounds reasonable, however `vendor-src` is a part of this repository and there is no package manager handling its dependencies. 

Meaning unfortunately that even if I go and fork the package in question and make fixes there, it will do absolutely nothing with regards to this package working. I'm afraid that I'll keep using my branch until I find an alternative. Thanks anyway.

**Comment by bodva** [comment]
@mnovozhylov 
Agree with @Norgul notice that the `vendor-src` is a part of this package because it is included here as a code directly, instead of dependencies.
It doesn't have the sense to link to the library because the library is outdated and looks like it does not have support anymore.

So for me, these two points mean you should maintain the code in the `vendor-src` the same way you maintain the code of the package itself.

**Pull request closed without merging**
